{% set name = "rosettasciio" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rosettasciio-{{ version }}.tar.gz
  sha256: 51291757879e3afe36c812e958f2ce978f2c419794b469d4dca09ccfd8e189b9

build:
  number: 0

outputs:
  - name: rosettasciio-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cython                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - python                                 # [build_platform != target_platform]
      host:
        - cython
        - pip
        - python
        - setuptools >=64.0
        - setuptools-scm >=8
        - wheel
      run:
        - python
        - dask-core >=2022.9.2
        - python-dateutil
        - numpy >=1.20.0
        - pint >=0.8
        - python-box >=6,<8
        - pyyaml
    test:
      imports:
        - rsciio
      commands:
        - pip check

  - name: rosettasciio
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('rosettasciio-base', exact=True) }}
        - python
        # blockfile
        - scikit-image >=0.18
        # eds-stream
        - sparse
        # hdf5
        - h5py >=2.3
        # arina
        - hdf5plugin
        # image
        - imageio >=2.16
        # mrcz
        # remove mrcz until the conda-forge feedstock is fixed
        #- mrcz
        - blosc
        # scalebar_export
        - matplotlib-scalebar
        - matplotlib-base >=3.6
        # speed
        - numba >=0.53
        # tiff
        - tifffile >=2022.7.28
        - imagecodecs >=2021.11.20
        # usid
        # dependencies resolution fails when building on windows, reason unknown
        #- pyUSID >=0.0.11
        # zspy
        - zarr >=2,<3
        # unpin when zarr is unpinned
        - numcodecs <0.16
    test:
      imports:
        - rsciio
        - pytest --pyargs rsciio
      requires:
        - pip
        - pytest-xdist
        - pooch

about:
  home: https://hyperspy.org/rosettasciio
  summary: Reading and writing scientific file formats
  dev_url: https://github.com/hyperspy/rosettasciio
  license: GPL-3.0-or-later
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
    - jlaehne
